
// This file has been generated by the GUI designer. Do not modify.
namespace SerpisAd
{
	public partial class ComboBoxHelper
	{
		public virtual void Build ()
		{
			// Action group SerpisAd.ComboBoxHelper
		}
	}
}
